name: Python application

on:
  push:
    branches: [ "lab-5" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Run unittests
      run: |
        python unit_tests.py
